window.casaDaPalavraCatalogo = {
  articles: [
    {
      title: "Parábola do Semeador (Lc 8, 4-15)",
      category: "Parábolas",
      subcategory: "",
      excerpt: "A parábola do Semeador revela como a Palavra de Deus encontra e transforma o coração humano.",
      htmlFile: "artigos/conteudos/parabolas/parabola-semeador.html",
    },
    {
      title: "O Fogo Sagrado (2 Mc 1, 19-23)",
      category: "História de Israel",
      subcategory: "Macabeus",
      excerpt: "A narrativa de 2 Macabeus destaca a importância do fogo que não se apaga como símbolo da presença de Deus.",
      htmlFile: "artigos/conteudos/historia_israel/macabeus/fogo-sagrado.html",
    },
    {
      title: "Dízimo: certeza de que a Esperança não decepciona (Rm 5,5)",
      category: "Vida Cristã",
      subcategory: "",
      excerpt: "A narrativa de 2 Macabeus destaca a importância do fogo que não se apaga como símbolo da presença de Deus.",
      htmlFile: "artigos\\conteudos\\vida_crista\\fundamentacao_biblica_dizimo.html",
    },
    {
      title: "O Reinado de Saul e a Crise do Sistema Tribal",
      category: "História de Israel",
      subcategory: "Período Monárquico",
      excerpt: "A passagem da liderança tribal à monarquia responde a desafios políticos e militares, mas também provoca tensões religiosas.",
      htmlFile: "artigos/conteudos/historia_israel/livro_historia_israel/01-saul.html",
    },
    {
      title: "O Reinado de Davi: Unificação, Jerusalém e Promessa Davídica",
      category: "História de Israel",
      subcategory: "Período Monárquico",
      excerpt: "Davi unifica as tribos, estabelece Jerusalém como capital e recebe a promessa que marca a história da monarquia.",
      htmlFile: "artigos/conteudos/historia_israel/livro_historia_israel/02-davi.html",
    },
    {
      title: "O Reinado de Salomão: Idade de Ouro e Crise Socioeconômica",
      category: "História de Israel",
      subcategory: "Período Monárquico",
      excerpt: "A prosperidade, o Templo e a expansão do reino convivem com custos sociais que alimentam a crise sucessória.",
      htmlFile: "artigos/conteudos/historia_israel/livro_historia_israel/03-salomao.html",
    },
    {
      title: "A Transformação da Sociedade de Israel e o Sentido Teológico da Monarquia",
      category: "História de Israel",
      subcategory: "Período Monárquico",
      excerpt: "Uma leitura teológica da transição da confederação tribal ao Estado dinástico e das mudanças sociais que acompanharam a monarquia.",
      htmlFile: "artigos/conteudos/historia_israel/livro_historia_israel/04-olhar_teologico_primeiros_anos_da_monarquia.html",
    },
    {
      title: "A Cisma Monárquica e a Consolidação dos Reinos de Israel e Judá",
      category: "História de Israel",
      subcategory: "Reino Dividido",
      excerpt: "A morte de Salomão desencadeia a ruptura do Reino Unificado e inaugura duas realidades distintas: Judá, estável e dinástico, e Israel, dinâmico e vulnerável.",
      htmlFile: "artigos/conteudos/historia_israel/livro_historia_israel/05-cisma.html",
    },
    {
      title: "A Casa de Amri: Apogeu Político-Militar e Apostasia Cultual",
      category: "História de Israel",
      subcategory: "Reino Dividido",
      excerpt: "A dinastia de Amri devolve estabilidade e poder a Israel, mas o preço é alto: o javismo é corroído por um baalismo de Estado combatido com vigor pelos profetas.",
      htmlFile: "artigos/conteudos/historia_israel/livro_historia_israel/06-casa_amri.html",
    },
    {
      title: "A Anarquia Final no Norte e a Derrocada Frente ao Império Assírio",
      category: "História de Israel",
      subcategory: "Reino Dividido",
      excerpt: "Após Jeroboão II, Israel mergulha em anarquia política e decadência moral, enquanto a Assíria de Tiglate-Pileser III avança com uma política de conquista permanente que culmina na queda de Samaria.",
      htmlFile: "artigos/conteudos/historia_israel/livro_historia_israel/07-invasao_assiria.html",
    },
    {
      title: "O Golpe de Jeú e o Declínio dos Reinos Divididos",
      category: "História de Israel",
      subcategory: "Reino Dividido",
      excerpt: "Ungido por um profeta, Jeú executa um golpe sangrento para extirpar o baalismo, mas sua purificação política abre um período de profunda fragilidade para Israel e Judá.",
      htmlFile: "artigos/conteudos/historia_israel/livro_historia_israel/08-jéu.html",
    },
    {
      title: "O Profetismo do Século VIII a.C.: Prosperidade Econômica e Ruína Ética",
      category: "História de Israel",
      subcategory: "Reino Dividido",
      excerpt: "Sob Jeroboão II e Ozias, Israel e Judá vivem uma era de prosperidade sem precedentes, enquanto Amós e Oseias denunciam uma desintegração social e religiosa que conduz ao juízo.",
      htmlFile: "artigos/conteudos/historia_israel/livro_historia_israel/09-profetismo_antes_assiria.html",
    },
  ],
  articleCategories: {
    Querigma: [
      "Amor de Deus", 
      "Pecado e Salvação", 
      "Fé e Conversão",
      "Senhorio de Jesus",
      "Batismo no Espírito Santo",
      "Amor aos irmãos"
    ],
    Parábolas: [],
    "História de Israel": [
      "Macabeus",
      "Período Monárquico",
      "Reino Dividido",
    ],
    "Vida Cristã": [
    ],
  },
  books: [
    { 
      title: "Bíblia Palavra Viva",
      author: "Paulus",
      category: "Bíblias de Estudo",
      description: "Um dos princípios dessa bíblia é: “A bíblia deve ser lida com a bíblia”. Ao buscar o comentário para uma passagem específica, frequentemente seremos direcionados a outras passagens que se relacionam com o texto inicialmente consultado",
      coverImage: "images/biblia_palavra_viva.png",
      amazonUrl: "https://www.amazon.com.br/B%C3%ADblia-Palavra-Viva-Capa-Pl%C3%A1stica/dp/6555626860"
    },
    { 
      title: "Bíblia do Peregrino",
      author: "Paulus",
      category: "Bíblias de Estudo",
      description: "Essa bíblia se destaca pela imensa quantidade de notas de rodapé, muitas delas com profundas discussões acerca do texto comentado",
      coverImage: "images/biblia_peregrino.png",
      amazonUrl: "https://www.amazon.com.br/Bíblia-do-Peregrino-Paulus-Editora/dp/8534920052"
    },
    { 
      title: "Bíblia Ave Maria Edição de Estudos",
      author: "Ave-Maria",
      category: "Bíblias de Estudo",
      description: "",
      coverImage: "images/biblia_ave_maria.png",
      amazonUrl: "https://www.amazon.com.br/B%C3%ADblia-Estudos-Ave-Maria-cap%C3%ADtulos-vers%C3%ADculos-ebook/dp/B0754LY4GS"
    },
    { 
      title: "Bíblia de Jerusalém",
      author: "Pauus",
      category: "Bíblias de Estudo",
      description: "",
      coverImage: "images/biblia_jerusalem.png",
      amazonUrl: "https://www.amazon.com.br/B%C3%ADblia-Jerusal%C3%A9m-Paulus-Editora/dp/8534919771"
    },
    { 
      title: "Bíblia TEB",
      author: "Loyola",
      category: "Bíblias de Estudo",
      description: "",
      coverImage: "images/biblia_teb.png",
      amazonUrl: "https://www.amazon.com.br/B%C3%ADblia-TEB-Estudo-Capa-dura/dp/8515030160"
    },
    { 
      title: "Comentário Histórico Cultural da Bíblia - Novo Testamento",
      author: "Vida Nova",
      category: "Comentários Bíblicos",
      description: "Apresenta comentários para o texto bíblico a partir do contexto e da cultura da época",
      coverImage: "images/histórico_cultural_NT.png",
      amazonUrl: "https://www.amazon.com.br/B%C3%ADblia-Palavra-Viva-Capa-Pl%C3%A1stica/dp/6555626860"
    },
    { 
      title: "Comentário Histórico Cultural da Bíblia - Antigo Testamento",
      author: "Vida NOva",
      category: "Comentários Bíblicos",
      description: "Apresenta comentários para o texto bíblico a partir do contexto e da cultura da época",
      coverImage: "images/histórico_cultural_AT.png",
      amazonUrl: "https://www.amazon.com.br/Bíblia-do-Peregrino-Paulus-Editora/dp/8534920052"
    },
    { 
      title: "Comentário Bíblico São Jerônimo - Novo Testamento",
      author: "Paulus",
      category: "Comentários Bíblicos",
      description: "Essa coleção é considerada uma enciclopédia bíblica, pois além de introduções à cada livro e comentários aos seus versículos, também é possível encontrar diversos artigos sistemáticos",
      coverImage: "images/jeronimo_NT.png",
      amazonUrl: "https://www.amazon.com.br/Novo-Coment%C3%A1rio-B%C3%ADblico-S%C3%A3o-Jer%C3%B4nimo/dp/8534946736"
    },
    { 
      title: "Comentário Bíblico São Jerônimo - Antigo Testamento",
      author: "Paulus",
      category: "Comentários Bíblicos",
      description: "Essa coleção é considerada uma enciclopédia bíblica, pois além de introduções à cada livro e comentários aos seus versículos, também é possível encontrar diversos artigos sistemáticos",
      coverImage: "images/jeronimo_AT.png",
      amazonUrl: "https://www.amazon.com.br/Catena-Aurea-Evangelho-S%C3%A3o-Mateus/dp/8584910913"
    },
    { 
      title: "Catena Áurea - Evangelho de São Mateus",
      author: "Ecclesiae",
      category: "Comentários da Bíblia feito por Santos",
      description: "Escrita/organizada por São Tomás de Aquino a pedido do Papa Urbano IV. Nela, podemos encontrar comentários dos Padres da Igreja (São Beda, São Jerônimo, São João Crisóstomo, Orígenes, Santo Agostinho, Santo Ambrósio, São Gregório Magno e muitos outros) para todas as perícopes dos quatro evangelhos",
      coverImage: "images/catena_mateus.png",
      amazonUrl: "https://www.amazon.com.br/B%C3%ADblia-Palavra-Viva-Capa-Pl%C3%A1stica/dp/6555626860"
    },
    { 
      title: "Catena Áurea - Evangelho de São Marcos",
      author: "Ecclesiae",
      category: "Comentários da Bíblia feito por Santos",
      description: "Escrita/organizada por São Tomás de Aquino a pedido do Papa Urbano IV. Nela, podemos encontrar comentários dos Padres da Igreja (São Beda, São Jerônimo, São João Crisóstomo, Orígenes, Santo Agostinho, Santo Ambrósio, São Gregório Magno e muitos outros) para todas as perícopes dos quatro evangelhos",
      coverImage: "images/catena_marcos.png",
      amazonUrl: "https://www.amazon.com.br/Catena-Aurea-Evangelho-S%C3%A3o-Marcos/dp/8584911243"
    },
    { 
      title: "Catena Áurea - Evangelho de São Lucas",
      author: "Ecclesiae",
      category: "Comentários da Bíblia feito por Santos",
      description: "Escrita/organizada por São Tomás de Aquino a pedido do Papa Urbano IV. Nela, podemos encontrar comentários dos Padres da Igreja (São Beda, São Jerônimo, São João Crisóstomo, Orígenes, Santo Agostinho, Santo Ambrósio, São Gregório Magno e muitos outros) para todas as perícopes dos quatro evangelhos",
      coverImage: "images/catena_lucas.png",
      amazonUrl: "https://www.amazon.com.br/Catena-Aurea-Vol-Evangelho-Lucas/dp/6587135102"
    },
    { 
      title: "Catena Áurea - Evangelho de São João",
      author: "Ecclesiae",
      category: "Comentários da Bíblia feito por Santos",
      description: "Escrita/organizada por São Tomás de Aquino a pedido do Papa Urbano IV. Nela, podemos encontrar comentários dos Padres da Igreja (São Beda, São Jerônimo, São João Crisóstomo, Orígenes, Santo Agostinho, Santo Ambrósio, São Gregório Magno e muitos outros) para todas as perícopes dos quatro evangelhos",
      coverImage: "images/catena_joao.png",
      amazonUrl: "https://www.amazon.com.br/Catena-Aurea-Vol-Evangelho-Jo%C3%A3o/dp/6587135277"
    },
    {
      title: "Patrística - Comentário às cartas de São Paulo - Vol. 27/1 (Volume 27)",
      author: "São João Crisóstomo",
      category: "Comentários da Bíblia feito por Santos",
      coverImage: "images/001_Patristica_-_Comentario_as_cartas_de_Sao_Paulo_-_Vol._27_1_Volume_27.png",
      description: "Faz parte da coleção patrística, publicada pela editora Paulus e apresenta as homilias de São João Crisóstomo, um dos maiores intérpretes do pensamento de São Paulo para o Oriente cristão, sobre os textos de todas as cartas Paulinas",
      amazonUrl: "https://www.amazon.com.br/Coment%C3%A1rio-%C3%A0s-Cartas-S%C3%A3o-Paulo/dp/8534929912"
    },
    {
      title: "Patrística - Comentário às cartas de São Paulo - Vol. 27/2 (Volume 27)",
      author: "São João Crisóstomo",
      category: "Comentários da Bíblia feito por Santos",
      coverImage: "images/002_Patristica_-_Comentario_as_cartas_de_Sao_Paulo_-_Vol._27_2_Volume_27.png",
      description: "Faz parte da coleção patrística, publicada pela editora Paulus e apresenta as homilias de São João Crisóstomo, um dos maiores intérpretes do pensamento de São Paulo para o Oriente cristão, sobre os textos de todas as cartas Paulinas",
      amazonUrl: "https://www.amazon.com.br/Coment%C3%A1rio-%C3%A0s-Cartas-S%C3%A3o-Paulo/dp/8534930457"
    },
    {
      title: "Patrística - Comentário às cartas de São Paulo - Vol. 27/3 (Volume 27)",
      author: "São João Crisóstomo",
      category: "Comentários da Bíblia feito por Santos",
      coverImage: "images/003_Patristica_-_Comentario_as_cartas_de_Sao_Paulo_-_Vol._27_3_Volume_27.png",
      description: "Faz parte da coleção patrística, publicada pela editora Paulus e apresenta as homilias de São João Crisóstomo, um dos maiores intérpretes do pensamento de São Paulo para o Oriente cristão, sobre os textos de todas as cartas Paulinas",
      amazonUrl: "https://www.amazon.com.br/Coment%C3%A1rio-%C3%A0s-Cartas-S%C3%A3o-Paulo/dp/8534930465"
    },
    {
      title: "O Livro do Gênesis - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/003_O_Livro_do_Genesis_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Livro-do-G%C3%AAnesis-Scott-Hahn/dp/8584910174"
    },
    {
      title: "O Livro do Êxodo - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/015_O_Livro_do_Exodo_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Livro-do-%C3%8Axodo-Scott-Hahn/dp/8584910298"
    },
    {
      title: "Deuteronômio - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/012_Deuteronomio_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Caderno-estudo-b%C3%ADblico-Scott-Hahn/dp/8584913157"
    },
    {
      title: "O Livro dos Juízes e O Livro de Rute - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch, Michael Barber",
      category: "Comentários de Scott Hahn",
      coverImage: "images/026_Juizes_e_Rute_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/livro-dos-Ju%C3%ADzes-Rute-Cadernos/dp/858491174X"
    },
    {
      title: "O Livro de Jó - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/017_Jo_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Livro-J%C3%B3-Cadernos-Estudo-B%C3%ADblico/dp/6587135498"
    },
    {
      title: "O Livro dos Salmos - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/025_Salmos_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/livro-dos-Salmos-Cadernos-Estudos/dp/8584912487"
    },
    {
      title: "Provérbios, Eclesiastes e Cântico dos Cânticos - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/018_Proverbios_Eclesiastes_e_Cantico_dos_Canticos_-_Caderno_de_Estudos_Biblicos.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/livro-Prov%C3%A9rbios-Eclesiastes-C%C3%A2ntico-C%C3%A2nticos/dp/6587135641"
    },
    {
      title: "Isaías - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/024_Isaias_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Caderno-estudo-b%C3%ADblico-Scott-Hahn/dp/8584913149"
    },
    {
      title: "O Livro de Daniel - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/005_Daniel_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/livro-Daniel-Cadernos-Estudo-B%C3%ADblico/dp/6587135927"
    },
    {
      title: "O Evangelho de São Mateus - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/scott_mateus.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Evangelho-S%C3%A3o-Matheus-Scott-Hahn/dp/8563160796"
    },
    {
      title: "O Evangelho de São Marcos - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/008_O_Evangelho_de_Sao_Marcos_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Evangelho-S%C3%A3o-Marcos-Scott-Hahn/dp/8563160842"
    },
    {
      title: "O Evangelho de São Lucas - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/010_O_Evangelho_de_Sao_Lucas_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Evangelho-S%C3%A3o-Lucas-Scott-Hahn/dp/8584910026"
    },
    {
      title: "O Evangelho de São João - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/002_O_Evangelho_de_Sao_Joao_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Evangelho-S%C3%A3o-Jo%C3%A3o-Scott-Hahn/dp/8584910123"
    },
    {
      title: "Atos dos Apóstolos - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/011_Atos_dos_Apostolos_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Livro-dos-Atos-Ap%C3%B3stolos-Cadernos/dp/8584910220"
    },
    {
      title: "Carta aos Romanos - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/006_Romanos_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Carta-Romanos-Cadernos-Estudos-B%C3%ADblicos/dp/8584910379"
    },
    {
      title: "As Cartas de São Paulo aos Coríntios - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/013_Corintios_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Cartas-S%C3%A3o-Paulo-aos-Cor%C3%ADntios/dp/8584910522"
    },
    {
      title: "Cartas aos Gálatas e aos Efésios - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/019_Galatas_e_Efesios_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Cartas-G%C3%A1latas-Ef%C3%A9sios-Caderno-B%C3%ADblico/dp/8584910689"
    },
    {
      title: "Cartas aos Filipenses, Colossenses e Filêmon - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/016_Filipenses_Colossenses_e_Filemon_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Cartas-Paulo-Filipenses-Colossenses-Fil%C3%AAmon/dp/8584910905"
    },
    {
      title: "Cartas aos Tessalonicenses, a Timóteo e a Tito - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/020_Tessalonicenses_Timoteo_e_Tito_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Cartas-Paulo-Tessalonicenses-Tim%C3%B3teo-Tito/dp/8584911499"
    },
    {
      title: "A Carta aos Hebreus - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/009_Hebreus_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Carta-Aos-Hebreus-Cadernos-B%C3%ADblico/dp/8584911502"
    },
    {
      title: "Cartas de São Tiago, São Pedro e São Judas - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/027_Cartas_De_Sao_Tiago_Sao_Pedro_e_Sao_Judas_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/Cartas-S%C3%A3o-Tiago-Pedro-Judas/dp/6587135048"
    },
    {
      title: "Cartas de São João e o Apocalipse - Caderno de Estudo Bíblico",
      author: "Scott Hahn, Curtis Mitch",
      category: "Comentários de Scott Hahn",
      coverImage: "images/014_Cartas_De_Sao_Joao_E_O_Apocalipse_-_Caderno_de_Estudo_Biblico.png",
      description: "Comentários baseados no catecismo da igreja católica, pensamentos dos padres da igreja, além das próprias reflexões de anos de estudo de Scott Hanh",
      amazonUrl: "https://www.amazon.com.br/As-Cartas-S%C3%A3o-Jo%C3%A3o-Apocalipse/dp/6587135021"
    },
    {
      title: "Parábolas do Evangelho",
      author: "São Gregório Magno",
      category: "Comentários da Bíblia feito por Santos",
      coverImage: "images/parabolas_gregorio.png",
      amazonUrl: "https://www.amazon.com.br/Par%C3%A1bolas-Evangelho-Melhor-Entender-Verdades/dp/8556383394"
    },
    {
      title: "Homilias Sobre Ezequiel",
      author: "São Gregório Magno",
      category: "Comentários da Bíblia feito por Santos",
      coverImage: "images/ezequiel_gregorio.png",
      amazonUrl: "https://www.amazon.com.br/Homilias-Sobre-Ezequiel-Greg%C3%B3rio-Magno/dp/6587135366"
    },
    {
      title: "História Santa - Catena áurea do Antigo Testamento (Tomo  1)",
      author: "Dom Jean de Monléon",
      category: "Comentários da Bíblia feito por Santos",
      coverImage: "images/historia_santa_tomo_1.png",
      description: "Composta pelo monge beneditino e exegeta francês Dom Jean de Monléon. O autor se apoiou em muitos pensamentos de santos como Santo Agostinho, São João Crisóstomo, Santo Efrém, Santo Ambrósio, dentre outros. Aqui, os comentários seguem aspectos da moral e da mística",
      amazonUrl: "https://www.amazon.com.br/Hist%C3%B3ria-santa-S-B-Jean-Monl%C3%A9on/dp/858491191X"
    },
    {
      title: "História Santa - Catena áurea do Antigo Testamento (Tomo  2)",
      author: "Dom Jean de Monléon",
      category: "Comentários da Bíblia feito por Santos",
      coverImage: "images/historia_santa_tomo_2.png",
      description: "Composta pelo monge beneditino e exegeta francês Dom Jean de Monléon. O autor se apoiou em muitos pensamentos de santos como Santo Agostinho, São João Crisóstomo, Santo Efrém, Santo Ambrósio, dentre outros. Aqui, os comentários seguem aspectos da moral e da mística",
      amazonUrl: "https://www.amazon.com.br/Hist%C3%B3ria-santa-S-B-Jean-Monl%C3%A9on/dp/8584912401"
    },
    {
      title: "Comentário Bíblico Vida Nova",
      author: "D. A. Carson",
      category: "Comentários Bíblicos",
      coverImage: "images/comentario_biblico_vida_nova.png",
      description: "",
      amazonUrl: "https://www.amazon.com.br/Coment%C3%A1rio-B%C3%ADblico-Vida-Nova-Carson/dp/8527504243"
    },
    {
      title: "Comentário do uso do Antigo Testamento no novo Testamento",
      author: "G. K. Beale",
      category: "Comentários Bíblicos",
      coverImage: "images/comentario_antigo_no_novo.png",
      description: "Contém comentários às passagens do Novo Testamento baseadas em passagens do Antigo Testamento. Em outras palavras, este Livro busca olhar para o Novo Testamento, a partir do Antigo.",
      amazonUrl: "https://www.amazon.com.br/Coment%C3%A1rio-Uso-Antigo-Testamento-Novo/dp/852750555X"
    },
    
  ],
  booksCategories: [
    "Bíblias de Estudo",
    "Comentários Bíblicos",
    "Comentários da Bíblia feito por Santos",
    "Comentários de Scott Hahn",
    "Temas Variados"
  ],
  pdfs: [
    // { title: "Título da publicação", author: "Autor", category: "Suma Teológica", file: "materiais/pdfs/publicacao.pdf" },
  ],
  videos: [
    {
      id: "46",
      title: "Helenismo e o Martírio de Eleazar",
      author: "@tarcisocastro19",
      category: "Senhorio de Jesus",
      embedUrl: "https://www.instagram.com/reel/Dd8hUWtsnZ9/embed/",
      link: "https://www.instagram.com/reel/Dd8hUWtsnZ9/",
    },
    {
      id: "45",
      title: "Potência, Ato e Senhorio de Jesus",
      author: "@tarcisocastro19",
      category: "Senhorio de Jesus",
      embedUrl: "https://www.instagram.com/reel/Dc0bTbGMtHM/embed/",
      link: "https://www.instagram.com/reel/Dc0bTbGMtHM/",
    },
    {
      id: "44",
      title: "O Espírito Santo e a conversão",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/p/Db-XF9Usg8w/embed/",
      link: "https://www.instagram.com/p/Db-XF9Usg8w/",
    },
    {
      id: "43",
      title: "Gedeão e o Espírito Santo",
      author: "@tarcisocastro19",
      category: "Batismo no Espírito Santo",
      embedUrl: "https://www.instagram.com/p/DLuPIKVOhBQ/embed/",
      link: "https://www.instagram.com/p/DLuPIKVOhBQ/",
    },
    {
      id: "42",
      title: "Como dar sentido ao sofrimento?",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DdJKOYWsXE-/embed/",
      link: "https://www.instagram.com/reel/DdJKOYWsXE-/",
    },
    {
      id: "41",
      title: "A cura de um leproso e um Deus que assume o nosso lugar",
      author: "@tarcisocastro19",
      category: "Amor de Deus",
      embedUrl: "https://www.instagram.com/reel/DakOdvtswin/embed/",
      link: "https://www.instagram.com/reel/DakOdvtswin/",
    },
    {
      id: "40",
      title: "Jesus, o quarto homem da fornalha",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DaSYxAtMwrL/embed/",
      link: "https://www.instagram.com/reel/DaSYxAtMwrL/",
    },
    {
      id: "39",
      title: "A intercessão dos santos: bases bíblicas",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DaALSxWsWme/embed/",
      link: "https://www.instagram.com/reel/DaALSxWsWme/",
    },
    {
      id: "38",
      title: "Bezeleel e o Espírito Santo",
      author: "@tarcisocastro19",
      category: "Batismo no Espírito Santo",
      embedUrl: "https://www.instagram.com/reel/DZeyyRKMTVm/embed/",
      link: "https://www.instagram.com/reel/DZeyyRKMTVm/",
    },
    {
      id: "37",
      title: "Frio ou quente, morno eu vomito",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DZKHwSqsLBS/embed/",
      link: "https://www.instagram.com/reel/DZKHwSqsLBS/",
    },
    {
      id: "36",
      title: "Pentecostes e a antibabel",
      author: "@tarcisocastro19",
      category: "Amor aos irmãos",
      embedUrl: "https://www.instagram.com/reel/DYmFmNHsEGb/embed/",
      link: "https://www.instagram.com/reel/DYmFmNHsEGb/",
    },
    {
      id: "35",
      title: "A provação e a imagem e semelhança de Deus",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DYCAjQ3M0K8/embed/",
      link: "https://www.instagram.com/reel/DYCAjQ3M0K8/",
    },
    {
      id: "34",
      title: "Jesus, a festa dos tabernáculos e a água que sacia nossa sede",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DXv_PBmsSvZ/embed/",
      link: "https://www.instagram.com/reel/DXv_PBmsSvZ/",
    },
    {
      id: "33",
      title: "O que é a eternidade",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DXgjaICDIxL/embed/",
      link: "https://www.instagram.com/reel/DXgjaICDIxL/",
    },
    {
      id: "32",
      title: "Por que Jesus quando apareceu ressuscitado à Maria Madalena disse: não me toques?",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DW6BENSjHm2/embed/",
      link: "https://www.instagram.com/reel/DW6BENSjHm2/",
    },
    {
      id: "31",
      title: "Por que Jesus recebeu vinagre na cruz?",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DWlWi2pDGaF/embed/",
      link: "https://www.instagram.com/reel/DWlWi2pDGaF/",
    },
    {
      id: "30",
      title: "O que significa Hosana e Bendito o que vem em nome do Senhor?",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DWgQTDajGof/embed/",
      link: "https://www.instagram.com/reel/DWgQTDajGof/",
    },
    {
      id: "29",
      title: "Deus nunca está atrasado: a ressurreição de Lázaro",
      author: "@tarcisocastro19",
      category: "Senhorio de Jesus",
      embedUrl: "https://www.instagram.com/reel/DWYe9sODEHU/embed/",
      link: "https://www.instagram.com/reel/DWYe9sODEHU/",
    },
    {
      id: "28",
      title: "São José e o Messias",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DWD2IhnjKBx/embed/",
      link: "https://www.instagram.com/reel/DWD2IhnjKBx/",
    },
    {
      id: "27",
      title: "Por que nem sempre Deus atende às nossas orações?",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DVNw1fuDCkM/embed/",
      link: "https://www.instagram.com/reel/DVNw1fuDCkM/",
    },
    {
      id: "26",
      title: "Quaresma, conversão e cabo de guerra",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DU7vB7BjCqC/embed/",
      link: "https://www.instagram.com/reel/DU7vB7BjCqC/",
    },
    {
      id: "25",
      title: "Jesus e o jumentinho na entrada de Jerusalém",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DUp99kMjKAW/embed/",
      link: "https://www.instagram.com/reel/DUp99kMjKAW/",
    },
    {
      id: "24",
      title: "Vontade de divina: manifesta e de beneplácito",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DUXsplSjGVz/embed/",
      link: "https://www.instagram.com/reel/DUXsplSjGVz/",
    },
    {
      id: "23",
      title: "Os 5 maridos da samaritana",
      author: "@tarcisocastro19",
      category: "Senhorio de Jesus",
      embedUrl: "https://www.instagram.com/reel/DTzuTA7jOU3/embed/",
      link: "https://www.instagram.com/reel/DTzuTA7jOU3/",
    },
    {
      id: "22",
      title: "O Natal, o sim de Jesus e o ato humano de Deus",
      author: "@tarcisocastro19",
      category: "Senhorio de Jesus",
      embedUrl: "https://www.instagram.com/reel/DSrtt37DP8P/embed/",
      link: "https://www.instagram.com/reel/DSrtt37DP8P/",
    },
    {
      id: "21",
      title: "Os pastores e a visita ao Salvador",
      author: "@tarcisocastro19",
      category: "Amor de Deus",
      embedUrl: "https://www.instagram.com/reel/DSZiPbljIEp/embed/",
      link: "https://www.instagram.com/reel/DSZiPbljIEp/",
    },
    {
      id: "20",
      title: "O Natal e a expectativa pelo Filho de Davi",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DR1k_KQDCd4/embed/",
      link: "https://www.instagram.com/reel/DR1k_KQDCd4/",
    },
    {
      id: "19",
      title: "A multiplicação e a liberdade do homem",
      author: "@tarcisocastro19",
      category: "Amor de Deus",
      embedUrl: "https://www.instagram.com/reel/DRO4YfcDKTF/embed/",
      link: "https://www.instagram.com/reel/DRO4YfcDKTF/",
    },
    {
      id: "18",
      title: "Por que Jesus é chamado de Filho do Homem?",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DQ_bjLwjHMS/embed/",
      link: "https://www.instagram.com/reel/DQ_bjLwjHMS/",
    },
    {
      id: "17",
      title: "A impenitência final e a graça de ter uma boa morte",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DQtfiEtDKqm/embed/",
      link: "https://www.instagram.com/reel/DQtfiEtDKqm/",
    },
    {
      id: "16",
      title: "Jesus, menor e igual ao Pai? Como?",
      author: "@tarcisocastro19",
      category: "Senhorio de Jesus",
      embedUrl: "https://www.instagram.com/reel/DQbXgU1jvWx/embed/",
      link: "https://www.instagram.com/reel/DQbXgU1jvWx/",
    },
    {
      id: "15",
      title: "O convite ao banquete e a justa medida: Lc 14, 16-24",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DQJcyJyAJ9G/embed/",
      link: "https://www.instagram.com/reel/DQJcyJyAJ9G/",
    },
    {
      id: "14",
      title: "Jesus tinha fé?",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DPlRoRkjlmm/embed/",
      link: "https://www.instagram.com/reel/DPlRoRkjlmm/",
    },
    {
      id: "13",
      title: "As 10 pragas do Egito",
      author: "@tarcisocastro19",
      category: "Senhorio de Jesus",
      embedUrl: "https://www.instagram.com/reel/DP3W5jRkS5r/embed/",
      link: "https://www.instagram.com/reel/DP3W5jRkS5r/",
    },
    {
      id: "12",
      title: "Por que devemos falar com Deus?",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DPTcNPejF1J/embed/",
      link: "https://www.instagram.com/reel/DPTcNPejF1J/",
    },
    {
      id: "11",
      title: "Da posse à entrega: a lei e o senhorio de Jesus",
      author: "@tarcisocastro19",
      category: "Senhorio de Jesus",
      embedUrl: "https://www.instagram.com/reel/DPBQcG3DoEJ/embed/",
      link: "https://www.instagram.com/reel/DPBQcG3DoEJ/",
    },
    {
      id: "10",
      title: "Justiça de Deus e preço de sangue",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DOvN9gHDuic/embed/",
      link: "https://www.instagram.com/reel/DOvN9gHDuic/",
    },
    {
      id: "9",
      title: "Ezequias e uma lição sobre confiança",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DN5Il7rjp7T/embed/",
      link: "https://www.instagram.com/reel/DN5Il7rjp7T/",
    },
    {
      id: "8",
      title: "Ansiedade e Reino dos Céus",
      author: "@tarcisocastro19",
      category: "Amor de Deus",
      embedUrl: "https://www.instagram.com/reel/DNnILS0uXt4/embed/",
      link: "https://www.instagram.com/reel/DNnILS0uXt4/",
    },
    {
      id: "7",
      title: "Maria, arca da aliança: parte 1",
      author: "@tarcisocastro19",
      category: "Maria",
      embedUrl: "https://www.instagram.com/reel/DNDE7HQOBo_/embed/",
      link: "https://www.instagram.com/reel/DNDE7HQOBo_/",
    },
    {
      id: "6",
      title: "Maria, arca da aliança: parte 2",
      author: "@tarcisocastro19",
      category: "Maria",
      embedUrl: "https://www.instagram.com/reel/DNFwYLbuu04/embed/",
      link: "https://www.instagram.com/reel/DNFwYLbuu04/",
    },
    {
      id: "5",
      title: "Maria, arca da aliança: parte 3",
      author: "@tarcisocastro19",
      category: "Maria",
      embedUrl: "https://www.instagram.com/reel/DNVHM6nuEwL/embed/",
      link: "https://www.instagram.com/reel/DNVHM6nuEwL/",
    },
    {
      id: "4",
      title: "Temos dado ao outro aquilo que ele merece?",
      author: "@tarcisocastro19",
      category: "Amor aos irmãos",
      embedUrl: "https://www.instagram.com/reel/DMxsTAkMrq3/embed/",
      link: "https://www.instagram.com/reel/DMxsTAkMrq3/",
    },
    {
      id: "3",
      title: "Afinal, o que é seguir a Cristo?",
      author: "@tarcisocastro19",
      category: "Fé e Conversão",
      embedUrl: "https://www.instagram.com/reel/DMfqfKYshYP/embed/",
      link: "https://www.instagram.com/reel/DMfqfKYshYP/",
    },
    {
      id: "2",
      title: "A profundidade da alma e o purgatório antes da morte",
      author: "@tarcisocastro19",
      category: "Pecado e Salvação",
      embedUrl: "https://www.instagram.com/reel/DMLuyUmv1Cc/embed/",
      link: "https://www.instagram.com/reel/DMLuyUmv1Cc/",
    },
    {
      id: "1",
      title: "As bodas de caná e a nova criação",
      author: "@tarcisocastro19",
      category: "Amor de Deus",
      embedUrl: "https://www.instagram.com/reel/DMAS7loOp6x/embed/",
      link: "https://www.instagram.com/reel/DMAS7loOp6x/",
    },
  ],
  videoCategories: [
    "Amor de Deus", 
    "Pecado e Salvação", 
    "Fé e Conversão",
    "Senhorio de Jesus",
    "Batismo no Espírito Santo",
    "Amor aos irmãos",
    "Maria"
  ],
};
